version: "3.7"

services:

  app:
    build:
      args:
        user: samara
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: epic-app
    restart: unless-stopped
    container_name: epic-app
    expose:
      - "9000"
    ports:
      - 9000:9000
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - default

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - default

  nginx:
    image: nginx:1.17-alpine
    container_name: epic-nginx
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  dbdata:
    driver: local
